project:
  type: website
  output-dir: _docs

website:
  title: "etielle: Declarative JSON-to-Relational Mapping in Python"
  sidebar:
    style: docked
    contents:
      - href: index.qmd
        text: Quickstart
      - href: docs/introduction-to-etl.qmd
        text: Introduction to ETL
      - href: docs/traversals.qmd
        text: Traversals
      - href: docs/transforms.qmd
        text: Transforms
      - href: docs/emissions.qmd
        text: Emissions
      - href: docs/relationships.qmd
        text: Relationships
      - href: docs/loading-data-into-a-database.qmd
        text: Database upserts
      - href: docs/developing-with-etielle.qmd
        text: Developing with etielle
  navbar:
    right:
      - icon: github
        href: https://github.com/promptly-technologies-llc/etielle
  page-footer:
    left: "Copyright 2025, Promptly Technologies, LLC. MIT License."
    right:
      - icon: github
        href: https://github.com/promptly-technologies-llc/etielle
format:
  html:
    theme: cosmo
    toc: true